### ISSUE TITLE
kas confligs with kerbal konstrut

### ISSUE THREAD

**Issue by tonimark** [ihsoft/KAS#223] opened 2018-07-04 09:16 UTC
after 1.4.4 the keys betwheen kas and kerbal konstuts confligs and kas replace the building key Ctrl + K with the kas debuger plz fix that key configuration i don't see the key in cfg settings

**Comment by ihsoft** [comment] 2018-07-04 09:33
I'm confused. What is the relation between `KSP 1.4.4` and `Ctrl+K`? Afaik, this key combination is not used by the stock game. If it's `kerbal konstructs` that use it, then it's a mods conflict situation. It can be solved by deprecating `KIS 0.6.*` version in favor of the `KAS 1.0 Beta`, which is now in the final stage before the release.

FYI. The support to `KAS 0.6.*` is discontinued.

**Comment by ihsoft** [comment] 2018-07-04 09:34
DUplicate of #222

**Closed by ihsoft** 2018-07-04 09:34 UTC
Labels: duplicate
