### ISSUE TITLE
Fuel transfer don't work inside vessel

### ISSUE THREAD

**Issue by vladtcvs** [ihsoft/KAS#280] opened 2019-09-16 10:59 UTC
Resources obeys crossfeed rules enabled

In vessel like this

Tank1 --- Smth --- Tank2
   |                             |
   |------- KAS pipe ---|

where Smth doesn't allow crossfeed, I can not move fuel between tanks. If Smth contains decoupler, then after decoupling it, 

Tank1 --- Smth1 --- Decoupler       Smth2 --- Tank2
   |                                                                      |
   |-------------------- KAS pipe -----------------------|

while pipe still connected, I can move fuel.

**Comment by ihsoft** [comment] 2019-09-16 20:44
* Which pipe you used for connection?
* Was that pipe in docked or undocked mode?
* How were you transferring fuel after decoupling?

Screenshots or a short video would help.

**Comment by vladtcvs** [comment] 2019-09-18 16:01
Pipe from RTS-1 and connector JS-1

I've tried both docked and undocked mode

After decoupling i have In and Out buttons on tanks

![Снимок экрана в 2019-09-18 18-57-23](https://user-images.githubusercontent.com/3390973/65164891-63e48f80-da46-11e9-88e4-a52715a47550.png)
![Снимок экрана в 2019-09-18 18-58-22](https://user-images.githubusercontent.com/3390973/65164892-647d2600-da46-11e9-9d99-eb6d823a5d49.png)

Also I've found other small bug - if you decouple in docked mode, you have do switch to undocked and to docked again.

**Comment by ihsoft** [comment] 2019-09-18 19:17
It seems on the bottom image RTS is in docked mode. In this mode the linked parts are treated as one vessel. And since they are now linked via RTS and not via a decoupler, the fuel flow is allowed. It's intended behavior.

**Comment by vladtcvs** [comment] 2019-09-18 19:18
So, is it possible to move fuel between tanks inside one vessel?

**Comment by ihsoft** [comment] 2019-09-18 20:59
Alas, no, it's not possible. In KSP parts can connect to each other at just one point. In your design left tank is connected to decouple, and decoupler is connected to the right tank. This two connections are used by the game to check if the fuel can flow. From the game's standpount, the RTS part is only connected to the right tank. Otherwise it would introduce a loop in the parts tree.

Btw, have you tried to replace RTS with a stock fuel pipe? Does it allow fuel transferring in this config?

**Comment by ihsoft** [comment] 2020-04-26 05:33
I filed a separate bug for the improper docking mode update: https://github.com/ihsoft/KAS/issues/289.

As for the crossfeed behavior, it works the same way with the stock fuel pipe. I don't see an easy way to make it without fighting with the stock game logic. Could you please give a real game use-case where such function would be useful? Are you trying to overcome decoupler limitations in EVA?

**Comment by ihsoft** [comment] 2021-06-28 05:22
The root cause has been fixed.

**Closed by ihsoft** 2021-06-28 05:22 UTC
